### ISSUE TITLE
TCGA Data Reports page has two bad links

### ISSUE THREAD

**Issue by slagelwa** [isb-cgc/readthedocs#76]
http://isb-cancer-genomics-cloud.readthedocs.io/en/latest/sections/data/data2/TCGA_Reports.html

The two dashboard links redirect to dead pages

**Comment by smrgit** [comment]
@toddpihl is all of this information gone forever?  any thoughts?

**Comment by toddpihl** [comment]
Yeah, these are definitely dead and gone.  I suppose we could like to the TCGA wiki (https://wiki.nci.nih.gov/display/TCGA), but even that is getting pretty obsolete and has a ton of links that will just 404.  

Probably the best scenario would be to point to GDC (maybe[ this page?](https://portal.gdc.cancer.gov/search/s?facetTab=cases) since NCI may archive the TCGA wiki without any real warning.

**Comment by smrgit** [comment]
I've removed this page entirely as part of a major restructuring and updating of the documentation.
