### ISSUE TITLE
couldn't download public TCGA tissue slides

### ISSUE THREAD

**Issue by malmajid** [isb-cgc/readthedocs#84]
Hi, 

I couldn't mount the public open data provided by NCI for the tcga project onto a folder in my google instance. Here is what I wrote: 

gcsfuse gs://isb-cgc-open/NCI-GDC/legacy/TCGA/TCGA-HNSC/Other/Tissue_slide_image testing_mounting/

**Comment by smrgit** [comment]
Did you create the mount directory first?  You would need to do something like (possibly using sudo):
```
mkdir /Volumes/isb-cgc-open
gcsfuse isb-cgc-open /Volumes/isb-cgc-open
```
(Note that you should leave off the "gs://" prefix.)  If successful, you should see something like:
```
Using mount point: /Volumes/isb-cgc-open
Opening GCS connection...
Opening bucket...
Mounting file system...
File system has been successfully mounted
```
(Note that these are based on notes from doing this on a Mac rather than on a GCE VM.)

Is it important to you that you mount this bucket/folder using gcsfuse rather than copying the files that you need to the VM temporarily (using "gsutil cp")?  What exactly is your use case?  I may be able to offer better advice if I know more about what you're trying to do.
